
project_id = "lpabxfhmsiadplgqrpym"
[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[functions]
[functions.seller_functions]
verify_jwt = true

[functions.admin_functions]
verify_jwt = true

[functions.delivery_functions]
verify_jwt = true
