// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpabxfhmsiadplgqrpym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwYWJ4Zmhtc2lhZHBsZ3FycHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDUyMjcsImV4cCI6MjA2MTg4MTIyN30.jp94HEoU8kNFdg80aLfxUW0GD99QE12_NuqGrFcaf-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);